language: cpp
dist: trusty
sudo: required

install:
  - sudo rm -r /opt/python/*
  - sudo apt-get -y install python-pip
  - which pip
  - sudo apt-get update
  - sudo apt-get -y install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra python-matplotlib pandoc
  - pip install sphinx numpydoc matplotlib nbsphinx==0.3.1 ipython==5.* --user --upgrade

script:
  # nbsphinx 0.3.1:
  - make html -C doc
  # now with nbsphinx 0.3.2:
  - pip install nbsphinx --user --upgrade
  - rm -r build
  - make html -C doc
