language: cpp
dist: trusty
sudo: required

install:
  - sudo apt-get update
  - sudo apt-get -y install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra python-matplotlib
  - sudo rm -r /opt/python/*
  - pip install sphinx numpydoc matplotlib nbsphinx --user --upgrade

script:
  - cd doc && make html

